
import = ["/Users/michaela/.config/alacritty/flat_remix.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
blur = false
opacity = 1.0
dynamic_title = true

[window.dimensions]
columns = 70
lines = 40

[mouse]
hide_when_typing = true

[font]
size = 18.0

[font.bold]
family = "Iosevka Term"

[font.italic]
family = "Iosevka Term"
style = "Italic"

[font.normal]
family = "Iosevka Term"
style = "Medium"

